var dir_4c4d319bfb6a1b985933b61bcbce5c83 =
[
    [ "acp_dai_dma.h", "acp__dai__dma_8h.html", "acp__dai__dma_8h" ],
    [ "afe-dai.h", "afe-dai_8h.html", "afe-dai_8h" ],
    [ "afe-drv.h", "afe-drv_8h.html", "afe-drv_8h" ],
    [ "afe-memif.h", "afe-memif_8h.html", "afe-memif_8h" ],
    [ "afe-sgen.h", "afe-sgen_8h.html", "afe-sgen_8h" ],
    [ "cache_attr.h", "cache__attr_8h.html", null ],
    [ "dmic.h", "dmic_8h.html", null ],
    [ "dw-dma.h", "dw-dma_8h.html", "dw-dma_8h" ],
    [ "edma.h", "edma_8h.html", "edma_8h" ],
    [ "esai.h", "esai_8h.html", "esai_8h" ],
    [ "gpio.h", "gpio_8h.html", "gpio_8h" ],
    [ "hda-dma.h", "hda-dma_8h.html", "hda-dma_8h" ],
    [ "hda.h", "hda_8h.html", "hda_8h" ],
    [ "interrupt-map.h", "interrupt-map_8h.html", "interrupt-map_8h" ],
    [ "iomux.h", "iomux_8h.html", "iomux_8h" ],
    [ "micfil.h", "micfil_8h.html", "micfil_8h" ],
    [ "mu.h", "mu_8h.html", "mu_8h" ],
    [ "pmc.h", "pmc_8h.html", null ],
    [ "sai.h", "sai_8h.html", "sai_8h" ],
    [ "sdma.h", "sdma_8h.html", "sdma_8h" ],
    [ "spi.h", "spi_8h.html", "spi_8h" ],
    [ "ssp.h", "ssp_8h.html", "ssp_8h" ]
];