var dir_db6073b5deb283ffef855790b268e831 =
[
    [ "a_law.h", "a__law_8h.html", "a__law_8h" ],
    [ "auditory.h", "auditory_8h.html", "auditory_8h" ],
    [ "cordic.h", "cordic_8h.html", "cordic_8h" ],
    [ "dct.h", "dct_8h.html", "dct_8h" ],
    [ "decibels.h", "decibels_8h.html", "decibels_8h" ],
    [ "exp_fcn.h", "exp__fcn_8h.html", "exp__fcn_8h" ],
    [ "fft.h", "fft_8h.html", "fft_8h" ],
    [ "fir_config.h", "fir__config_8h.html", null ],
    [ "fir_generic.h", "fir__generic_8h.html", null ],
    [ "fir_hifi2ep.h", "fir__hifi2ep_8h.html", null ],
    [ "fir_hifi3.h", "fir__hifi3_8h.html", null ],
    [ "icomplex16.h", "icomplex16_8h.html", "icomplex16_8h" ],
    [ "icomplex32.h", "icomplex32_8h.html", "icomplex32_8h" ],
    [ "iir_df1.h", "iir__df1_8h.html", "iir__df1_8h" ],
    [ "iir_df1_generic.h", "iir__df1__generic_8h.html", "iir__df1__generic_8h" ],
    [ "iir_df1_hifi3.h", "iir__df1__hifi3_8h.html", "iir__df1__hifi3_8h" ],
    [ "iir_df2t.h", "iir__df2t_8h.html", "iir__df2t_8h" ],
    [ "iir_df2t_generic.h", "iir__df2t__generic_8h.html", "iir__df2t__generic_8h" ],
    [ "iir_df2t_hifi3.h", "iir__df2t__hifi3_8h.html", "iir__df2t__hifi3_8h" ],
    [ "log.h", "log_8h.html", "log_8h" ],
    [ "lut_trig.h", "lut__trig_8h.html", "lut__trig_8h" ],
    [ "matrix.h", "matrix_8h.html", "matrix_8h" ],
    [ "mu_law.h", "mu__law_8h.html", "mu__law_8h" ],
    [ "numbers.h", "numbers_8h.html", "numbers_8h" ],
    [ "power.h", "power_8h.html", "power_8h" ],
    [ "sqrt.h", "sqrt_8h.html", "sqrt_8h" ],
    [ "trig.h", "trig_8h.html", "trig_8h" ],
    [ "window.h", "window_8h.html", "window_8h" ]
];