var searchData=
[
  ['mat_5fmatrix_5f16b_0',['mat_matrix_16b',['../structmat__matrix__16b.html',1,'']]],
  ['mfcc_5fbuffer_1',['mfcc_buffer',['../structmfcc__buffer.html',1,'']]],
  ['mfcc_5fcepstral_5flifter_2',['mfcc_cepstral_lifter',['../structmfcc__cepstral__lifter.html',1,'']]],
  ['mfcc_5fcomp_5fdata_3',['mfcc_comp_data',['../structmfcc__comp__data.html',1,'']]],
  ['mfcc_5fdata_5fheader_4',['mfcc_data_header',['../structmfcc__data__header.html',1,'']]],
  ['mfcc_5ffft_5',['mfcc_fft',['../structmfcc__fft.html',1,'']]],
  ['mfcc_5fpre_5femph_6',['mfcc_pre_emph',['../structmfcc__pre__emph.html',1,'']]],
  ['mfcc_5fstate_7',['mfcc_state',['../structmfcc__state.html',1,'']]],
  ['mfcc_5fvad_5fstate_8',['mfcc_vad_state',['../structmfcc__vad__state.html',1,'']]],
  ['mic_5fprivacy_5fdata_9',['mic_privacy_data',['../structmic__privacy__data.html',1,'']]],
  ['mic_5fprivacy_5fsettings_10',['mic_privacy_settings',['../structmic__privacy__settings.html',1,'']]],
  ['micfil_5fpdata_11',['micfil_pdata',['../structmicfil__pdata.html',1,'']]],
  ['mod_5falloc_5fctx_12',['mod_alloc_ctx',['../structmod__alloc__ctx.html',1,'']]],
  ['module_5fendpoint_5fops_13',['module_endpoint_ops',['../structmodule__endpoint__ops.html',1,'']]],
  ['module_5fparam_14',['module_param',['../structmodule__param.html',1,'']]],
  ['module_5fprocessing_5fdata_15',['module_processing_data',['../structmodule__processing__data.html',1,'']]],
  ['module_5fresource_16',['module_resource',['../structmodule__resource.html',1,'']]],
  ['module_5fresources_17',['module_resources',['../structmodule__resources.html',1,'']]],
  ['moduleinitialsettings_18',['ModuleInitialSettings',['../classintel__adsp_1_1_module_initial_settings.html',1,'intel_adsp']]],
  ['moduleinitialsettingsconcrete_19',['ModuleInitialSettingsConcrete',['../structdsp__fw_1_1_module_initial_settings_concrete.html',1,'dsp_fw']]],
  ['moduleinitialsettingsinterface_20',['ModuleInitialSettingsInterface',['../structintel__adsp_1_1_module_initial_settings_interface.html',1,'intel_adsp']]],
  ['moduleinitialsettingsitem_21',['ModuleInitialSettingsItem',['../structintel__adsp_1_1_module_initial_settings_item.html',1,'intel_adsp']]],
  ['moduleinitialsettingsitem_3c_20in_5fpins_5fformat_20_3e_22',['ModuleInitialSettingsItem&lt; IN_PINS_FORMAT &gt;',['../structintel__adsp_1_1_module_initial_settings_item_3_01_i_n___p_i_n_s___f_o_r_m_a_t_01_4.html',1,'intel_adsp']]],
  ['moduleinitialsettingsitem_3c_20legacy_5fstruct_20_3e_23',['ModuleInitialSettingsItem&lt; LEGACY_STRUCT &gt;',['../structintel__adsp_1_1_module_initial_settings_item_3_01_l_e_g_a_c_y___s_t_r_u_c_t_01_4.html',1,'intel_adsp']]],
  ['moduleinitialsettingsitem_3c_20out_5fpins_5fformat_20_3e_24',['ModuleInitialSettingsItem&lt; OUT_PINS_FORMAT &gt;',['../structintel__adsp_1_1_module_initial_settings_item_3_01_o_u_t___p_i_n_s___f_o_r_m_a_t_01_4.html',1,'intel_adsp']]],
  ['mtk_5fbase_5fafe_25',['mtk_base_afe',['../structmtk__base__afe.html',1,'']]],
  ['mtk_5fbase_5fafe_5fdai_26',['mtk_base_afe_dai',['../structmtk__base__afe__dai.html',1,'']]],
  ['mtk_5fbase_5fafe_5firq_27',['mtk_base_afe_irq',['../structmtk__base__afe__irq.html',1,'']]],
  ['mtk_5fbase_5fafe_5fmemif_28',['mtk_base_afe_memif',['../structmtk__base__afe__memif.html',1,'']]],
  ['mtk_5fbase_5fafe_5fplatform_29',['mtk_base_afe_platform',['../structmtk__base__afe__platform.html',1,'']]],
  ['mtk_5fbase_5firq_5fdata_30',['mtk_base_irq_data',['../structmtk__base__irq__data.html',1,'']]],
  ['mtk_5fbase_5fmemif_5fdata_31',['mtk_base_memif_data',['../structmtk__base__memif__data.html',1,'']]]
];
