var searchData=
[
  ['sai_2eh_0',['sai.h',['../sai_8h.html',1,'']]],
  ['schedule_2eh_1',['schedule.h',['../ipc_2schedule_8h.html',1,'(Global Namespace)'],['../schedule_2schedule_8h.html',1,'(Global Namespace)']]],
  ['sdma_2eh_2',['sdma.h',['../sdma_8h.html',1,'']]],
  ['selector_2eh_3',['selector.h',['../sof_2audio_2selector_8h.html',1,'(Global Namespace)'],['../user_2selector_8h.html',1,'(Global Namespace)']]],
  ['sink_5fapi_2eh_4',['sink_api.h',['../sink__api_8h.html',1,'']]],
  ['sink_5fsource_5futils_2eh_5',['sink_source_utils.h',['../sink__source__utils_8h.html',1,'']]],
  ['smart_5famp_2eh_6',['smart_amp.h',['../sof_2audio_2smart__amp_2smart__amp_8h.html',1,'(Global Namespace)'],['../user_2smart__amp_8h.html',1,'(Global Namespace)']]],
  ['smart_5famp_5ftest_2eh_7',['smart_amp_test.h',['../smart__amp__test_8h.html',1,'']]],
  ['sof_2eh_8',['sof.h',['../sof_8h.html',1,'']]],
  ['sof_5fdma_2eh_9',['sof_dma.h',['../sof__dma_8h.html',1,'']]],
  ['sound_5fdose_2eh_10',['sound_dose.h',['../sound__dose_8h.html',1,'']]],
  ['source_5fapi_2eh_11',['source_api.h',['../source__api_8h.html',1,'']]],
  ['spi_2eh_12',['spi.h',['../spi_8h.html',1,'']]],
  ['spinlock_2eh_13',['spinlock.h',['../spinlock_8h.html',1,'']]],
  ['sqrt_2eh_14',['sqrt.h',['../sqrt_8h.html',1,'']]],
  ['ssp_2eh_15',['ssp.h',['../ssp_8h.html',1,'']]],
  ['stream_2eh_16',['stream.h',['../ipc_2stream_8h.html',1,'(Global Namespace)'],['../sof_2audio_2stream_8h.html',1,'(Global Namespace)']]],
  ['string_2eh_17',['string.h',['../string_8h.html',1,'']]],
  ['string_5fmacro_2eh_18',['string_macro.h',['../xtos_2include_2rtos_2string__macro_8h.html',1,'(Global Namespace)'],['../zephyr_2include_2rtos_2string__macro_8h.html',1,'(Global Namespace)']]],
  ['symbol_2eh_19',['symbol.h',['../symbol_8h.html',1,'']]],
  ['system_5fagent_2eh_20',['system_agent.h',['../system__agent_8h.html',1,'']]],
  ['system_5fagent_5finterface_2eh_21',['system_agent_interface.h',['../system__agent__interface_8h.html',1,'']]],
  ['system_5ferror_2eh_22',['system_error.h',['../system__error_8h.html',1,'']]],
  ['system_5fservice_2eh_23',['system_service.h',['../system__service_8h.html',1,'']]]
];
