var searchData=
[
  ['dai_2damd_2eh_0',['dai-amd.h',['../dai-amd_8h.html',1,'']]],
  ['dai_2dimx_2eh_1',['dai-imx.h',['../dai-imx_8h.html',1,'']]],
  ['dai_2dintel_2eh_2',['dai-intel.h',['../dai-intel_8h.html',1,'']]],
  ['dai_2dlegacy_2eh_3',['dai-legacy.h',['../dai-legacy_8h.html',1,'']]],
  ['dai_2dmediatek_2eh_4',['dai-mediatek.h',['../dai-mediatek_8h.html',1,'']]],
  ['dai_2dzephyr_2eh_5',['dai-zephyr.h',['../dai-zephyr_8h.html',1,'']]],
  ['dai_2eh_6',['dai.h',['../src_2include_2ipc_2dai_8h.html',1,'(Global Namespace)'],['../zephyr_2include_2sof_2lib_2dai_8h.html',1,'(Global Namespace)']]],
  ['data_5fblob_2eh_7',['data_blob.h',['../data__blob_8h.html',1,'']]],
  ['dct_2eh_8',['dct.h',['../dct_8h.html',1,'']]],
  ['debug_2eh_9',['debug.h',['../ipc_2debug_8h.html',1,'(Global Namespace)'],['../sof_2debug_2debug_8h.html',1,'(Global Namespace)']]],
  ['debug_5fstream_2eh_10',['debug_stream.h',['../debug__stream_8h.html',1,'']]],
  ['debug_5fstream_5fslot_2eh_11',['debug_stream_slot.h',['../debug__stream__slot_8h.html',1,'']]],
  ['debug_5fstream_5ftext_5fmsg_2eh_12',['debug_stream_text_msg.h',['../debug__stream__text__msg_8h.html',1,'']]],
  ['debug_5fstream_5fthread_5finfo_2eh_13',['debug_stream_thread_info.h',['../debug__stream__thread__info_8h.html',1,'']]],
  ['decibels_2eh_14',['decibels.h',['../decibels_8h.html',1,'']]],
  ['detect_5ftest_2eh_15',['detect_test.h',['../detect__test_8h.html',1,'']]],
  ['dma_2dlegacy_2eh_16',['dma-legacy.h',['../dma-legacy_8h.html',1,'']]],
  ['dma_2dtrace_2eh_17',['dma-trace.h',['../dma-trace_8h.html',1,'']]],
  ['dma_2eh_18',['dma.h',['../dma_8h.html',1,'']]],
  ['dmic_2eh_19',['dmic.h',['../dmic_8h.html',1,'']]],
  ['dp_5fschedule_2eh_20',['dp_schedule.h',['../dp__schedule_8h.html',1,'']]],
  ['driver_2eh_21',['driver.h',['../driver_8h.html',1,'']]],
  ['dw_2ddma_2eh_22',['dw-dma.h',['../dw-dma_8h.html',1,'']]]
];
